<?php


/**
 * This class defines the structure of the 'item2itemcategory' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class Item2itemcategoryTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Item2itemcategoryTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('item2itemcategory');
		$this->setPhpName('Item2itemcategory');
		$this->setClassname('Item2itemcategory');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('ITEMCATEGORY_ID', 'ItemcategoryId', 'INTEGER', 'itemcategory', 'ID', false, null, null);
		$this->addColumn('ITEM_ID', 'ItemId', 'INTEGER', true, null, null);
		$this->addForeignKey('ITEM_TYPE', 'ItemType', 'INTEGER', 'itemtypes', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Itemcategory', 'Itemcategory', RelationMap::MANY_TO_ONE, array('itemcategory_id' => 'id', ), null, null);
    $this->addRelation('Itemtypes', 'Itemtypes', RelationMap::MANY_TO_ONE, array('item_type' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Item2itemcategoryTableMap
