<?php

/**
 * Base class that represents a row from the 'itemcategory' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * @package    lib.model.om
 */
abstract class BaseItemcategory extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ItemcategoryPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the itemcategory_id field.
	 * @var        int
	 */
	protected $itemcategory_id;

	/**
	 * The value for the show field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $show;

	/**
	 * The value for the order field.
	 * @var        int
	 */
	protected $order;

	/**
	 * The value for the code field.
	 * @var        string
	 */
	protected $code;

	/**
	 * @var        Itemcategory
	 */
	protected $aItemcategoryRelatedByItemcategoryId;

	/**
	 * @var        array Itemcategory[] Collection to store aggregation of Itemcategory objects.
	 */
	protected $collItemcategorysRelatedByItemcategoryId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItemcategorysRelatedByItemcategoryId.
	 */
	private $lastItemcategoryRelatedByItemcategoryIdCriteria = null;

	/**
	 * @var        array ItemcategoryI18n[] Collection to store aggregation of ItemcategoryI18n objects.
	 */
	protected $collItemcategoryI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItemcategoryI18ns.
	 */
	private $lastItemcategoryI18nCriteria = null;

	/**
	 * @var        array Item2itemcategory[] Collection to store aggregation of Item2itemcategory objects.
	 */
	protected $collItem2itemcategorys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collItem2itemcategorys.
	 */
	private $lastItem2itemcategoryCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ItemcategoryPeer';

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->show = true;
	}

	/**
	 * Initializes internal state of BaseItemcategory object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [itemcategory_id] column value.
	 * 
	 * @return     int
	 */
	public function getItemcategoryId()
	{
		return $this->itemcategory_id;
	}

	/**
	 * Get the [show] column value.
	 * 
	 * @return     boolean
	 */
	public function getShow()
	{
		return $this->show;
	}

	/**
	 * Get the [order] column value.
	 * 
	 * @return     int
	 */
	public function getOrder()
	{
		return $this->order;
	}

	/**
	 * Get the [code] column value.
	 * 
	 * @return     string
	 */
	public function getCode()
	{
		return $this->code;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Itemcategory The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			if ($this->id === null && $v === '') {
			} else {
			  $this->modifiedColumns[] = ItemcategoryPeer::ID;
			}
			$this->id = $v;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [itemcategory_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Itemcategory The current object (for fluent API support)
	 */
	public function setItemcategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->itemcategory_id !== $v) {
			if ($this->itemcategory_id === null && $v === '') {
			} else {
			  $this->modifiedColumns[] = ItemcategoryPeer::ITEMCATEGORY_ID;
			}
			$this->itemcategory_id = $v;
		}

		if ($this->aItemcategoryRelatedByItemcategoryId !== null && $this->aItemcategoryRelatedByItemcategoryId->getId() !== $v) {
			$this->aItemcategoryRelatedByItemcategoryId = null;
		}

		return $this;
	} // setItemcategoryId()

	/**
	 * Set the value of [show] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Itemcategory The current object (for fluent API support)
	 */
	public function setShow($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->show !== $v || $this->isNew()) {
			if ($this->show === null && $v === '') {
			} else {
			  $this->modifiedColumns[] = ItemcategoryPeer::SHOW;
			}
			$this->show = $v;
		}

		return $this;
	} // setShow()

	/**
	 * Set the value of [order] column.
	 * 
	 * @param      int $v new value
	 * @return     Itemcategory The current object (for fluent API support)
	 */
	public function setOrder($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->order !== $v) {
			if ($this->order === null && $v === '') {
			} else {
			  $this->modifiedColumns[] = ItemcategoryPeer::ORDER;
			}
			$this->order = $v;
		}

		return $this;
	} // setOrder()

	/**
	 * Set the value of [code] column.
	 * 
	 * @param      string $v new value
	 * @return     Itemcategory The current object (for fluent API support)
	 */
	public function setCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->code !== $v) {
			if ($this->code === null && $v === '') {
			} else {
			  $this->modifiedColumns[] = ItemcategoryPeer::CODE;
			}
			$this->code = $v;
		}

		return $this;
	} // setCode()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->show !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->itemcategory_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->show = ($row[$startcol + 2] !== null) ? (boolean) $row[$startcol + 2] : null;
			$this->order = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->code = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = ItemcategoryPeer::NUM_COLUMNS - ItemcategoryPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Itemcategory object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aItemcategoryRelatedByItemcategoryId !== null && $this->itemcategory_id !== $this->aItemcategoryRelatedByItemcategoryId->getId()) {
			$this->aItemcategoryRelatedByItemcategoryId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ItemcategoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ItemcategoryPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aItemcategoryRelatedByItemcategoryId = null;
			$this->collItemcategorysRelatedByItemcategoryId = null;
			$this->lastItemcategoryRelatedByItemcategoryIdCriteria = null;

			$this->collItemcategoryI18ns = null;
			$this->lastItemcategoryI18nCriteria = null;

			$this->collItem2itemcategorys = null;
			$this->lastItem2itemcategoryCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ItemcategoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseItemcategory:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ItemcategoryPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseItemcategory:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ItemcategoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseItemcategory:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseItemcategory:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ItemcategoryPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aItemcategoryRelatedByItemcategoryId !== null) {
				if ($this->aItemcategoryRelatedByItemcategoryId->isModified() || $this->aItemcategoryRelatedByItemcategoryId->isNew()) {
					$affectedRows += $this->aItemcategoryRelatedByItemcategoryId->save($con);
				}
				$this->setItemcategoryRelatedByItemcategoryId($this->aItemcategoryRelatedByItemcategoryId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ItemcategoryPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					// if i18n object is new and all fields are empty we do not save it into DB
					$has_non_empty_fields = false;
					$only_service_fields_modified = true;
					$is_i18n = false;
					foreach ($this->getModifiedColumns() as $modified_column) {
						// news_i18n.UPDATED_AT_EXTRA -> UpdatedAtExtra
						if (strstr($modified_column, 'i18n')) {
							$is_i18n = true;
						}
						$modified_column_name = preg_replace("/^[^\.]+\./", '', $modified_column);
						// we do not take into account changing of some of the fields
						if (in_array($modified_column_name, array('ID', 'CULTURE', 'UPDATED_AT', 'UPDATED_AT_EXTRA'))) {
							continue;
						}
						$only_service_fields_modified = false;
						// news_i18n.UPDATED_AT_EXTRA -> news_i18n.UpdatedAtExtra							
						$modified_column_name_parts = explode('_', $modified_column_name);
						$modified_column_name = '';
						foreach ($modified_column_name_parts as $part) {
							$modified_column_name .= ucfirst(strtolower($part));
						}

						$value = $this->getByName($modified_column_name);						

						if ($value) {
							$has_non_empty_fields = true;
							break;
						}
					}
					if ($has_non_empty_fields || ($only_service_fields_modified && !$is_i18n)) {
						$pk = ItemcategoryPeer::doInsert($this, $con);
						$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

						$this->setId($pk);  //[IMV] update autoincrement primary key

						$this->setNew(false);
					}
				} else {
					$affectedRows += ItemcategoryPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collItemcategorysRelatedByItemcategoryId !== null) {
				foreach ($this->collItemcategorysRelatedByItemcategoryId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collItemcategoryI18ns !== null) {
				foreach ($this->collItemcategoryI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collItem2itemcategorys !== null) {
				foreach ($this->collItem2itemcategorys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aItemcategoryRelatedByItemcategoryId !== null) {
				if (!$this->aItemcategoryRelatedByItemcategoryId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aItemcategoryRelatedByItemcategoryId->getValidationFailures());
				}
			}


			if (($retval = ItemcategoryPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collItemcategorysRelatedByItemcategoryId !== null) {
					foreach ($this->collItemcategorysRelatedByItemcategoryId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collItemcategoryI18ns !== null) {
					foreach ($this->collItemcategoryI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collItem2itemcategorys !== null) {
					foreach ($this->collItem2itemcategorys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ItemcategoryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getItemcategoryId();
				break;
			case 2:
				return $this->getShow();
				break;
			case 3:
				return $this->getOrder();
				break;
			case 4:
				return $this->getCode();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ItemcategoryPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getItemcategoryId(),
			$keys[2] => $this->getShow(),
			$keys[3] => $this->getOrder(),
			$keys[4] => $this->getCode(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ItemcategoryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setItemcategoryId($value);
				break;
			case 2:
				$this->setShow($value);
				break;
			case 3:
				$this->setOrder($value);
				break;
			case 4:
				$this->setCode($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ItemcategoryPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setItemcategoryId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setShow($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setOrder($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCode($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);

		if ($this->isColumnModified(ItemcategoryPeer::ID)) $criteria->add(ItemcategoryPeer::ID, $this->id);
		if ($this->isColumnModified(ItemcategoryPeer::ITEMCATEGORY_ID)) $criteria->add(ItemcategoryPeer::ITEMCATEGORY_ID, $this->itemcategory_id);
		if ($this->isColumnModified(ItemcategoryPeer::SHOW)) $criteria->add(ItemcategoryPeer::SHOW, $this->show);
		if ($this->isColumnModified(ItemcategoryPeer::ORDER)) $criteria->add(ItemcategoryPeer::ORDER, $this->order);
		if ($this->isColumnModified(ItemcategoryPeer::CODE)) $criteria->add(ItemcategoryPeer::CODE, $this->code);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);

		$criteria->add(ItemcategoryPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Itemcategory (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setItemcategoryId($this->itemcategory_id);

		$copyObj->setShow($this->show);

		$copyObj->setOrder($this->order);

		$copyObj->setCode($this->code);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getItemcategorysRelatedByItemcategoryId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItemcategoryRelatedByItemcategoryId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getItemcategoryI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItemcategoryI18n($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getItem2itemcategorys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addItem2itemcategory($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Itemcategory Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ItemcategoryPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ItemcategoryPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Itemcategory object.
	 *
	 * @param      Itemcategory $v
	 * @return     Itemcategory The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setItemcategoryRelatedByItemcategoryId(Itemcategory $v = null)
	{
		if ($v === null) {
			$this->setItemcategoryId(NULL);
		} else {
			$this->setItemcategoryId($v->getId());
		}

		$this->aItemcategoryRelatedByItemcategoryId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Itemcategory object, it will not be re-added.
		if ($v !== null) {
			$v->addItemcategoryRelatedByItemcategoryId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Itemcategory object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Itemcategory The associated Itemcategory object.
	 * @throws     PropelException
	 */
	public function getItemcategoryRelatedByItemcategoryId(PropelPDO $con = null)
	{
		if ($this->aItemcategoryRelatedByItemcategoryId === null && ($this->itemcategory_id !== null)) {
			$this->aItemcategoryRelatedByItemcategoryId = ItemcategoryPeer::retrieveByPk($this->itemcategory_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aItemcategoryRelatedByItemcategoryId->addItemcategorysRelatedByItemcategoryId($this);
			 */
		}
		return $this->aItemcategoryRelatedByItemcategoryId;
	}

	/**
	 * Clears out the collItemcategorysRelatedByItemcategoryId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItemcategorysRelatedByItemcategoryId()
	 */
	public function clearItemcategorysRelatedByItemcategoryId()
	{
		$this->collItemcategorysRelatedByItemcategoryId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItemcategorysRelatedByItemcategoryId collection (array).
	 *
	 * By default this just sets the collItemcategorysRelatedByItemcategoryId collection to an empty array (like clearcollItemcategorysRelatedByItemcategoryId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItemcategorysRelatedByItemcategoryId()
	{
		$this->collItemcategorysRelatedByItemcategoryId = array();
	}

	/**
	 * Gets an array of Itemcategory objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Itemcategory has previously been saved, it will retrieve
	 * related ItemcategorysRelatedByItemcategoryId from storage. If this Itemcategory is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Itemcategory[]
	 * @throws     PropelException
	 */
	public function getItemcategorysRelatedByItemcategoryId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItemcategorysRelatedByItemcategoryId === null) {
			if ($this->isNew()) {
			   $this->collItemcategorysRelatedByItemcategoryId = array();
			} else {

				$criteria->add(ItemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				ItemcategoryPeer::addSelectColumns($criteria);
				$this->collItemcategorysRelatedByItemcategoryId = ItemcategoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ItemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				ItemcategoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastItemcategoryRelatedByItemcategoryIdCriteria) || !$this->lastItemcategoryRelatedByItemcategoryIdCriteria->equals($criteria)) {
					$this->collItemcategorysRelatedByItemcategoryId = ItemcategoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItemcategoryRelatedByItemcategoryIdCriteria = $criteria;
		return $this->collItemcategorysRelatedByItemcategoryId;
	}

	/**
	 * Returns the number of related Itemcategory objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Itemcategory objects.
	 * @throws     PropelException
	 */
	public function countItemcategorysRelatedByItemcategoryId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItemcategorysRelatedByItemcategoryId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ItemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				$count = ItemcategoryPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ItemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				if (!isset($this->lastItemcategoryRelatedByItemcategoryIdCriteria) || !$this->lastItemcategoryRelatedByItemcategoryIdCriteria->equals($criteria)) {
					$count = ItemcategoryPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collItemcategorysRelatedByItemcategoryId);
				}
			} else {
				$count = count($this->collItemcategorysRelatedByItemcategoryId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Itemcategory object to this object
	 * through the Itemcategory foreign key attribute.
	 *
	 * @param      Itemcategory $l Itemcategory
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItemcategoryRelatedByItemcategoryId(Itemcategory $l)
	{
		if ($this->collItemcategorysRelatedByItemcategoryId === null) {
			$this->initItemcategorysRelatedByItemcategoryId();
		}
		if (!in_array($l, $this->collItemcategorysRelatedByItemcategoryId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItemcategorysRelatedByItemcategoryId, $l);
			$l->setItemcategoryRelatedByItemcategoryId($this);
		}
	}

	/**
	 * Clears out the collItemcategoryI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItemcategoryI18ns()
	 */
	public function clearItemcategoryI18ns()
	{
		$this->collItemcategoryI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItemcategoryI18ns collection (array).
	 *
	 * By default this just sets the collItemcategoryI18ns collection to an empty array (like clearcollItemcategoryI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItemcategoryI18ns()
	{
		$this->collItemcategoryI18ns = array();
	}

	/**
	 * Gets an array of ItemcategoryI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Itemcategory has previously been saved, it will retrieve
	 * related ItemcategoryI18ns from storage. If this Itemcategory is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ItemcategoryI18n[]
	 * @throws     PropelException
	 */
	public function getItemcategoryI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItemcategoryI18ns === null) {
			if ($this->isNew()) {
			   $this->collItemcategoryI18ns = array();
			} else {

				$criteria->add(ItemcategoryI18nPeer::ID, $this->id);

				ItemcategoryI18nPeer::addSelectColumns($criteria);
				$this->collItemcategoryI18ns = ItemcategoryI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ItemcategoryI18nPeer::ID, $this->id);

				ItemcategoryI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastItemcategoryI18nCriteria) || !$this->lastItemcategoryI18nCriteria->equals($criteria)) {
					$this->collItemcategoryI18ns = ItemcategoryI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItemcategoryI18nCriteria = $criteria;
		return $this->collItemcategoryI18ns;
	}

	/**
	 * Returns the number of related ItemcategoryI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ItemcategoryI18n objects.
	 * @throws     PropelException
	 */
	public function countItemcategoryI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItemcategoryI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ItemcategoryI18nPeer::ID, $this->id);

				$count = ItemcategoryI18nPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ItemcategoryI18nPeer::ID, $this->id);

				if (!isset($this->lastItemcategoryI18nCriteria) || !$this->lastItemcategoryI18nCriteria->equals($criteria)) {
					$count = ItemcategoryI18nPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collItemcategoryI18ns);
				}
			} else {
				$count = count($this->collItemcategoryI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ItemcategoryI18n object to this object
	 * through the ItemcategoryI18n foreign key attribute.
	 *
	 * @param      ItemcategoryI18n $l ItemcategoryI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItemcategoryI18n(ItemcategoryI18n $l)
	{
		if ($this->collItemcategoryI18ns === null) {
			$this->initItemcategoryI18ns();
		}
		if (!in_array($l, $this->collItemcategoryI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItemcategoryI18ns, $l);
			$l->setItemcategory($this);
		}
	}

	/**
	 * Clears out the collItem2itemcategorys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addItem2itemcategorys()
	 */
	public function clearItem2itemcategorys()
	{
		$this->collItem2itemcategorys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collItem2itemcategorys collection (array).
	 *
	 * By default this just sets the collItem2itemcategorys collection to an empty array (like clearcollItem2itemcategorys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initItem2itemcategorys()
	{
		$this->collItem2itemcategorys = array();
	}

	/**
	 * Gets an array of Item2itemcategory objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Itemcategory has previously been saved, it will retrieve
	 * related Item2itemcategorys from storage. If this Itemcategory is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Item2itemcategory[]
	 * @throws     PropelException
	 */
	public function getItem2itemcategorys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItem2itemcategorys === null) {
			if ($this->isNew()) {
			   $this->collItem2itemcategorys = array();
			} else {

				$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				Item2itemcategoryPeer::addSelectColumns($criteria);
				$this->collItem2itemcategorys = Item2itemcategoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				Item2itemcategoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastItem2itemcategoryCriteria) || !$this->lastItem2itemcategoryCriteria->equals($criteria)) {
					$this->collItem2itemcategorys = Item2itemcategoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastItem2itemcategoryCriteria = $criteria;
		return $this->collItem2itemcategorys;
	}

	/**
	 * Returns the number of related Item2itemcategory objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Item2itemcategory objects.
	 * @throws     PropelException
	 */
	public function countItem2itemcategorys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collItem2itemcategorys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				$count = Item2itemcategoryPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				if (!isset($this->lastItem2itemcategoryCriteria) || !$this->lastItem2itemcategoryCriteria->equals($criteria)) {
					$count = Item2itemcategoryPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collItem2itemcategorys);
				}
			} else {
				$count = count($this->collItem2itemcategorys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Item2itemcategory object to this object
	 * through the Item2itemcategory foreign key attribute.
	 *
	 * @param      Item2itemcategory $l Item2itemcategory
	 * @return     void
	 * @throws     PropelException
	 */
	public function addItem2itemcategory(Item2itemcategory $l)
	{
		if ($this->collItem2itemcategorys === null) {
			$this->initItem2itemcategorys();
		}
		if (!in_array($l, $this->collItem2itemcategorys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collItem2itemcategorys, $l);
			$l->setItemcategory($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Itemcategory is new, it will return
	 * an empty collection; or if this Itemcategory has previously
	 * been saved, it will retrieve related Item2itemcategorys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Itemcategory.
	 */
	public function getItem2itemcategorysJoinItemtypes($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ItemcategoryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collItem2itemcategorys === null) {
			if ($this->isNew()) {
				$this->collItem2itemcategorys = array();
			} else {

				$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

				$this->collItem2itemcategorys = Item2itemcategoryPeer::doSelectJoinItemtypes($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(Item2itemcategoryPeer::ITEMCATEGORY_ID, $this->id);

			if (!isset($this->lastItem2itemcategoryCriteria) || !$this->lastItem2itemcategoryCriteria->equals($criteria)) {
				$this->collItem2itemcategorys = Item2itemcategoryPeer::doSelectJoinItemtypes($criteria, $con, $join_behavior);
			}
		}
		$this->lastItem2itemcategoryCriteria = $criteria;

		return $this->collItem2itemcategorys;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collItemcategorysRelatedByItemcategoryId) {
				foreach ((array) $this->collItemcategorysRelatedByItemcategoryId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collItemcategoryI18ns) {
				foreach ((array) $this->collItemcategoryI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collItem2itemcategorys) {
				foreach ((array) $this->collItem2itemcategorys as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collItemcategorysRelatedByItemcategoryId = null;
		$this->collItemcategoryI18ns = null;
		$this->collItem2itemcategorys = null;
			$this->aItemcategoryRelatedByItemcategoryId = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseItemcategory:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseItemcategory::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return Itemcategory
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "title" value from the current {@link ItemcategoryI18n}.
	 */
	public function getTitle($culture = null)
	{
	  return $this->getCurrentItemcategoryI18n($culture)->getTitle();
	}
	
	/**
	 * Sets the "title" value of the current {@link ItemcategoryI18n}.
	 *
	 * @return Itemcategory
	 */
	public function setTitle($value, $culture = null)
	{
	  $this->getCurrentItemcategoryI18n($culture)->setTitle($value);
	  return $this;
	}
	
	/**
	 * Returns the "items_count" value from the current {@link ItemcategoryI18n}.
	 */
	public function getItemsCount($culture = null)
	{
	  return $this->getCurrentItemcategoryI18n($culture)->getItemsCount();
	}
	
	/**
	 * Sets the "items_count" value of the current {@link ItemcategoryI18n}.
	 *
	 * @return Itemcategory
	 */
	public function setItemsCount($value, $culture = null)
	{
	  $this->getCurrentItemcategoryI18n($culture)->setItemsCount($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return ItemcategoryI18n
	 */
	public function getCurrentItemcategoryI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : ItemcategoryI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->setItemcategoryI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->setItemcategoryI18nForCulture(new ItemcategoryI18n(), $culture);
	      $this->current_i18n[$culture]->setCulture($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function setItemcategoryI18nForCulture(ItemcategoryI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addItemcategoryI18n($object);
	}

} // BaseItemcategory
