# Предполагается, что у каждого модуля есть одноимённый route, используется при формировании файлов переводов
# Некоторые названия маршрутов используются в SiperCache при очистке кэша

main:
  url:  /:sf_culture/
  param: { module: news, action: main }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
frontend:
  url:  /:sf_culture/
  param: { module: news, action: main }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

version_full:
  url:  /:sf_culture/version/full
  param: { module: news, action: main }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

# дополнительные маршруты новостей идут до default, чтобы они срабатывали раньше
news_index:
  url:   /:sf_culture/news/index/*
  param: { module: news, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
news:
  url:   /:sf_culture/news/index/*
  param: { module: news, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
news_show:
  url:   /:sf_culture/news/show/*
  param: { module: news, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
# teachings
teachings_show:
  url:   /:sf_culture/teachings/show/*
  param: { module: news, action: teachings }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
# books
books_show:
  url:   /:sf_culture/books/show/*
  param: { module: news, action: books }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
# stoires
stories_show:
  url:   /:sf_culture/stories/show/*
  param: { module: news, action: stories }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
# projects
projects_index:
  url:   /:sf_culture/news/projects/*
  param: { module: news, action: index, itemcategory: projects }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
projects_show:
  url:   /:sf_culture/projects/show/*
  param: { module: news, action: projects }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

#photoalbum_index:
#  url:   /:sf_culture/photo/albums/*
#  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photoalbum_index:
  url:   /:sf_culture/photoalbums/index/*
  param: { module: photo, action: albums }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photoalbum_show:
  url:   /:sf_culture/photoalbum/show/*
  param: { module: photo, action: album }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

feed:
  url:   /:sf_culture/feed/index/*
  param: { module: news, action: feed }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

# должен быть выше default
revisionhistory:
  url:   /:sf_culture/revision/show/*
  param: { module: revisionhistory, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }


default:
  url:   /:sf_culture/:module/:action/*
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

chat:
  url:   /:sf_culture/chat
  param: { module: chat, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

news_rss:
  url:   /:sf_culture/news/rss
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

project:
  url:   /:sf_culture/project
  param: { module: project, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photo_index:
  url:   /:sf_culture/photo/index
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photo:
  url:   /:sf_culture/photo/index
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photo_show:
  url:   /:sf_culture/photo/show
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photo_view:
  url:   /:sf_culture/photo/view
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

photo_map:
  url:   /:sf_culture/photo/map
  param: { module: photo, action: map }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

video_index:
  url:   /:sf_culture/video/index/*
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

video_show:
  url:   /:sf_culture/video/show
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

biography:
  url:   /:sf_culture/biography
  param: { module: biography, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

sangha:
  url:   /:sf_culture/sangha
  param: { module: contactus, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

links:
  url:   /:sf_culture/links/show
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

search:
  url:   /:sf_culture/search
  param: { module: search, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

sf_captcha:
  url:   /captcha
  param: { module: sfCaptcha, action: index }

encyclopedia:
  url:   /:sf_culture/encyclopedia
  param: { module: encyclopedia, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

blessing:
  url:   /:sf_culture/blessing
  param: { module: blessing, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

faq:
  url:   /:sf_culture/faq
  param: { module: faq, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

#translation_fundraising:
#  url:   /:sf_culture/translation_fundraising
#  param: { module: translation_fundraising, action: show }
#  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

social_tools:
  url:   /:sf_culture/social_tools
  param: { module: social_tools, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

religious_forest:
  url:   /:sf_culture/religious_forest
  param: { module: religious_forest, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

audio_index:
  url:   /:sf_culture/audio/index/*
  param: { module: audio, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
audio:
  url:   /:sf_culture/audio/index
  param: { module: audio, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

audio_show:
  url:   /:sf_culture/audio/show
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

documents_index:
  url:   /:sf_culture/documents/index/*
  param: { module: documents, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }
documents:
  url:   /:sf_culture/documents/index
  param: { module: documents, action: index }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

audio_show:
  url:   /:sf_culture/audio/show
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

donation:
  url:   /:sf_culture/donations
  param: { module: donation, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

servers:
  url:   /:sf_culture/servers
  param: { module: servers, action: show }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

offer_translation:
  url:   /:sf_culture/offer_translation
  param: { module: text, action: offertranslationfields }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

js:
  url:   /:sf_culture/js
  param: { module: text, action: js }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }

# Ошибка 404
error404:
  url:   /:sf_culture/*
  param: { module: default, action: error404 }
  requirements: { sf_culture: (?:en|ru|cs|hu|sk|uk|es|pl|fr|zh_CN|vi|de|it|ja|es|et|ne|bn|he|zh_TW|de) }