generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Item2itemcategory
    theme:            default
    
    list:
      max_per_page: 100
      filters:  [itemcategory_id, item_id]
      sort: [id, desc]
      display: [itemcategory_id, itemcategory, item_id, _item_title, _item_type]
      title:   Item2itemcategory
      object_actions:
        _edit:  ~
        _delete: ~
     
    edit:
      display:
        "NONE": [itemcategory_id, item_type, item_id]