<?php

require 'lib/model/om/BaseAnnouncementsPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'announcements' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AnnouncementsPeer extends BaseAnnouncementsPeer {

  // число элементов в блоке Последнее
  const LATEST_COUNT 			= 1;
  // количество элементов в списке
  const ITEMS_PER_PAGE 			= 30;
  // short version title length
  const SHORT_LENGTH 			= 200;
  // url title max length
  const URL_MAX_LENGTH 			= 100;

  /**
   * Добавляет условие, при котором элемент отображается на языке пользователя
   *
   * @param unknown_type $c
   */
  public static function addVisibleCriteria($c)
  {
    $c->add( AnnouncementsPeer::SHOW, 1 );

    $culture = sfContext::getInstance()->getUser()->getCulture();

    $c_extra = $c->getNewCriterion(AnnouncementsI18nPeer::TITLE, '', Criteria::NOT_EQUAL);
    $c_extra->addAnd( $c->getNewCriterion(AnnouncementsI18nPeer::CULTURE, $culture) );

    $c_extra->addOr( $c->getNewCriterion(AnnouncementsPeer::ALL_CULTURES, 1) );

	$c->add($c_extra);
  }

  /**
   * Для RSS: добавляет условие, при котором элемент отображается на языке пользователя
   *
   * @param unknown_type $c
   */
  public static function addRssVisibleCriteria($c)
  {
    self::addVisibleCriteria($c);
  }

} // AnnouncementsPeer
