<?php

require 'lib/model/om/BaseAnnouncementsI18nPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'announcements_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AnnouncementsI18nPeer extends BaseAnnouncementsI18nPeer {

} // AnnouncementsI18nPeer
