<?php

require 'lib/model/om/BaseContactusPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'contactus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ContactusPeer extends BaseContactusPeer {
    
    /**
     * Get FB link
     *
     * @param unknown_type $fb_group
     * @return unknown
     */
	public static function getFbLink( $fb_group )
	{
	  return "http://www.facebook.com/{$fb_group}";
	}    
	
	/**
     * Get Twitter link
     *
     * @param unknown_type $fb_group
     * @return unknown
     */
	public static function getTwitterLink( $twitter_group )
	{
	  return "http://twitter.com/{$twitter_group}";
	}	
	
	/**
     * Get Google link
     *
     * @param unknown_type $fb_group
     * @return unknown
     */
	public static function getGoogleLink( $google_group )
	{
	  return "http://groups.google.com/group/{$google_group}";
	}
} // ContactusPeer
