<?php

require 'lib/model/om/BaseDocumentsPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'documents' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DocumentsPeer extends BaseDocumentsPeer {

  // число элементов в блоке Последнее
  const LATEST_COUNT 			= 3;
  // количество элементов в списке
  const ITEMS_PER_PAGE 			= 10;
  
  // ссылка на файл в удалённом хранилище
  //const REMOTE_URL 		= 'http://k002.kiwi6.com/uploads/hotlink/';
  const DOCUMENTS_DIR 		= '/uploads/documents/';
  
  // ссылка на скачивание из удалённого хранилища
  //const REMOTE_DOWNLOAD_URL		= 'http://k002.kiwi6.com/download/';
  
  /**
   * Добавляет условие, при котором элемент отображается на языке пользователя
   *
   * @param unknown_type $c
   */
  public static function addVisibleCriteria($c)
  {  
    $c->add( DocumentsPeer::SHOW, 1 );    
    $c->add( DocumentsPeer::FILE, '', Criteria::NOT_EQUAL );
    //$c->add( DocumentsI18nPeer::TITLE, '', Criteria::NOT_EQUAL );
    
    $c_all_cultueres = $c->getNewCriterion(DocumentsI18nPeer::TITLE, '', Criteria::NOT_EQUAL);
    $c_all_cultueres->addOr( $c->getNewCriterion(DocumentsPeer::ALL_CULTURES, 1) );

	$c->add($c_all_cultueres);
  }
  
  /**
   * Для RSS: добавляет условие, при котором элемент отображается на языке пользователя
   *
   * @param unknown_type $c
   */
  public static function addRssVisibleCriteria($c)
  {  
    self::addVisibleCriteria($c);
  }
	
} // DocumentsPeer
