<?php

require 'lib/model/om/BaseDocumentsI18nPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'documents_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DocumentsI18nPeer extends BaseDocumentsI18nPeer {

} // DocumentsI18nPeer
