<?php

require 'lib/model/om/BaseItemcategoryPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'itemcategory' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ItemcategoryPeer extends BaseItemcategoryPeer {
	
  /**
   * Build a tree from given list of Itemcategory elements
   *
   * @param unknown_type $itemcategory_list
   * @param unknown_type $itemcategory_el
   * @return unknown
   */
  public static function buildTree( $list, $element = null, $level = 0 )
  {
  	$next_level = $level + 1;
  	$tree_element    = array();
  	
  	if ($element) {
  	  $tree_element['object'] = $element; //'$list_item';
  	  $tree_element['level']  = $level;
  	}
  	
  	foreach ($list as $list_item) {
  		
      if ($level) {
      	
	    if ($list_item->getItemcategoryId() == $element->getId()) {
	      $new_tree_element           = array();
	  	  $new_tree_element['object'] = $list_item;
	  	  $new_tree_element['level']  = $next_level;
          $children 			      = ItemcategoryPeer::buildTree($list, $list_item, $next_level);
          if ($children) {
            $tree_element['children'][] = $children;
          }
        }
        
      } else {
      	
        // first level - choose elements without parent only
        if (!$list_item->getItemcategoryId()) {
          $tree_element[] = ItemcategoryPeer::buildTree($list, $list_item, $next_level);
        }
        
      }
    }
  	
  	return $tree_element;
  } 
  
} // ItemcategoryPeer
