<?php

require 'lib/model/om/BaseItem2itemcategoryPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'item2itemcategory' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Item2itemcategoryPeer extends BaseItem2itemcategoryPeer {
    
  /**
   * Get item categories by item type and Id
   * @param type $item_type
   * @param type $item_id
   */
  public static function getItemCategories($item_type, $item_id)
  {
    $c = new Criteria();
    $c->addJoin(Item2itemcategoryPeer::ITEMCATEGORY_ID, ItemcategoryPeer::ID);
    
    // Photos are connected to it's Photoalbum
    if ($item_type == ItemtypesPeer::ITEM_TYPE_PHOTO) {
      $c->add(Item2itemcategoryPeer::ITEM_TYPE, ItemtypesPeer::ITEM_TYPE_PHOTOALBUM);
      $c->addJoin(PhotoPeer::PHOTOALBUM_ID, Item2itemcategoryPeer::ITEM_ID);
      $c->add(PhotoPeer::ID, $item_id);
    } else {
      $c->add(Item2itemcategoryPeer::ITEM_TYPE, $item_type);
      $c->add(Item2itemcategoryPeer::ITEM_ID, $item_id);
    }

    $itemcategory_list = ItemcategoryPeer::doSelectWithI18n($c);
    
    return $itemcategory_list;
  }
  
} // Item2itemcategoryPeer
