<?php

require 'lib/model/om/BaseItem2itemcategory.php';


/**
 * Skeleton subclass for representing a row from the 'item2itemcategory' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Item2itemcategory extends BaseItem2itemcategory {
  public function getItemTypeName()
  {
  	return ItemtypesPeer::getItemTypeName( $this->getItemType() );
  }  
  
  public function getItemTitle()
  {  	
  	return Item2itemPeer::getItemTitle( $this->getItemTypeName(), $this->getItemId() );
  }
} // Item2itemcategory
