<?php

require 'lib/model/om/BaseLocationlink.php';


/**
 * Skeleton subclass for representing a row from the 'locationlink' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Locationlink extends BaseLocationlink {

	/**
	 * Initializes internal state of Locationlink object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	/**
	 * Get location.
	 *
	 */
	public function getLocation()
	{
		return LocationPeer::retrieveByPk($this->getLocationId());
	}

	/**
	 * Get upto location.
	 *
	 */
	public function getUptoLocation()
	{
		return LocationPeer::retrieveByPk($this->getUptoLocationId());
	}

} // Locationlink
