<?php

require 'lib/model/om/BaseLocationI18n.php';


/**
 * Skeleton subclass for representing a row from the 'location_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LocationI18n extends BaseLocationI18n {

} // LocationI18n
