# если неожиданно #
# ./symfony propel:build-sql  #
# перестаёт создвать SQL по данному файлу - причина может быть в комментариях. - какой-то косяк в #
# $this->lines = explode("\n", $this->cleanup($value)); #
# /lib/symfony/yaml/sfYamlParser.php #
# 
# и проверить, что кодировка UTF-8
#

propel:

  text:
    id:               ~
    created_at:       ~

  text_i18n:
    title:            { type: varchar(255), required: true }
    body:             { type: longvarchar }
    
  itemtypes:
    id:               ~
    name:             { type: varchar(10), required: true }

  item2item:
    id:               ~
    item1_id:         { type: integer, required: true, index: true }
    item1_type:       { type: integer, required: true, foreignTable: itemtypes, foreignReference: id, index: true }
    item2_id:         { type: integer, required: true, index: true }
    item2_type:       { type: integer, required: true, foreignTable: itemtypes, foreignReference: id, index: true }
    
  news:
    id:               ~
    date:             { type: date }
    updated_at:       ~
    show:             { type: boolean, defaultValue: true }
    order:            { type: integer, required: true }
    img:              { type: varchar(255) }
    full_path:        { type: varchar(255) }
    thumb_path:       { type: varchar(255) }
#    is_teaching:      { type: boolean, default: 0 }
    original:         { type: longvarchar, required: true }
    type:             { type: integer, required: true, foreignTable: newstypes, foreignReference: id, index: true, default: 1 }
    _indexes:
      updated_at:     [updated_at]
      date:           [date]
      show:           [show]
      order:          [order] 

  news_i18n:
    updated_at_extra:       ~ 
    title:            { type: longvarchar, required: true }
    shortbody:        { type: longvarchar, required: true }
    body:             { type: longvarchar, required: true }
    author:           { type: varchar(255) }
    translated_by:    { type: varchar(255) }
    link:             { type: varchar(255) }
    extradate:        { type: varchar(255) }
    doc:              { type: varchar(255) }
    _indexes:
      culture:              [culture]
      updated_at_extra:     [updated_at_extra]
      body:                 [body]
    
  newstypes:
    id:               ~
    name:             { type: varchar(20), required: true }

  upload:
    id:               ~
    title:            { type: varchar(255), required: true }
    url:              { type: varchar(255) }

  photo:
    id:               ~
    photoalbum_id:    ~
    created_at:       { type: timestamp }
    updated_at:       ~
    show:             { type: boolean, defaultValue: true }
    order:            { type: integer, required: true }
    img:              { type: varchar(255) }
    full_path:        { type: varchar(255) }
    preview_path:     { type: varchar(255) }
    thumb_path:       { type: varchar(255) }
    link:             { type: varchar(255) }
    width:            { type: integer }
    height:           { type: integer }
    _indexes:
      photoalbum_id:  [photoalbum_id]
      updated_at:     [updated_at]
      show:           [show]
      img:            [img]
      full_path:      [full_path]
      preview_path:   [preview_path]
      thumb_path:     [thumb_path]
    _uniques:
      photoalbum_order:     [photoalbum_id, order]

  photo_i18n:
    updated_at_extra: ~
    title:            { type: longvarchar }
    body:             { type: longvarchar }
    author:           { type: varchar(255) }
    _indexes:
      updated_at_extra:     [updated_at_extra]
    
  photoalbum:
    id:               ~
    created_at:       ~
    show:             { type: boolean, defaultValue: true }
    order:            { type: integer, required: true }
    _indexes:
      show:      [show]
      order:     [order]

  photoalbum_i18n:
    title:            { type: longvarchar }
    body:             { type: longvarchar }
    author:           { type: varchar(255) }    

  video:
    id:               ~
    created_at:       ~
    updated_at:       ~
    show:             { type: boolean, defaultValue: true }
    order:            { type: integer, required: true }
    link:             { type: varchar(255) }
    all_cultures:     { type: boolean, default: 0 }
    _indexes:
      updated_at:    [updated_at]
      show:          [show]
      order:         [order]
      all_cultures:  [all_cultures]

  video_i18n:
    updated_at_extra: ~
    img:              { type: varchar(255), required: true }
    code:             { type: longvarchar, required: true }
    title:            { type: longvarchar }
    body:             { type: longvarchar }
    author:           { type: varchar(255) }
    _indexes:
      updated_at_extra:     [updated_at_extra]
      code:                 [code]

  quote:
    id:               ~

  quote_i18n:
    title:            { type: longvarchar, required: true }

  audio:
    id:               ~
    created_at:       ~
    updated_at:       ~
    show:             { type: boolean, defaultValue: true }
    file:             { type: varchar(255), required: true }
    remote:           { type: varchar(255) }
    size:             { type: float }
    duration:         { type: float }
    order:            { type: integer, required: true, index: true }
    _indexes:
      updated_at:     [updated_at]
      show:           [show]
      file:           [file]
      remote:         [remote]
    
  audio_i18n:
    updated_at_extra: ~
    title:            { type: longvarchar }
    body:             { type: longvarchar }
    author:           { type: longvarchar }
    _indexes:
      updated_at_extra:     [updated_at_extra]
      
  revisionhistory:
    id:               ~
    created_at:       ~
    show:             { type: boolean, defaultValue: true }
    page_mnemonic:    { type: varchar(255) }
    body:             { type: longvarchar }
    _indexes:
      main:          [page_mnemonic, show]
      
  documents:
    id:               ~
    created_at:       ~
    updated_at:       ~
    news_id:          ~
    show:             { type: boolean, defaultValue: true }
    file:             { type: varchar(255), required: true }
    size:             { type: float }
    order:            { type: integer, required: true, index: true }
    all_cultures:     { type: boolean, default: 0 }
    _indexes:
      updated_at:     [updated_at]
      show:           [show]
      all_cultures:   [all_cultures]
    _uniques:
      file:           [file]
    
  documents_i18n:
    updated_at_extra: ~
    title:            { type: longvarchar }
# not used
    body:             { type: longvarchar }
    _indexes:
      updated_at_extra:     [updated_at_extra]
      
  clearcache:
    id:               ~
    created_at:       ~
    sf_guard_user_id:  { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id }
    item_id:           { type: integer, required: true }
    itemtypes_id:      ~
    item_culture:      { type: varchar(7), required: true }
    cleared:           { type: boolean, default: 0 }
    document_created:  { type: boolean, default: 0 }
    _indexes:
      sf_guard_user_id:  [sf_guard_user_id]
      item_id:           [item_id]
      itemtypes_id:      [itemtypes_id]
      item_culture:      [item_culture]
      cleared:           [cleared]
      document_created:  [document_created]