generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Documents
    theme:            default

    list:
      peer_method: doSelectWithI18n
      max_per_page: 50
      sort: [order, desc]
      display: [id, show, order, =file, title, news_id, all_cultures, created_at, _itemcategory_list, _item2item_list]
      title:   Documents
      filters: [show, news_id, all_cultures]
      object_actions:
        _edit:
        _delete:

    edit:
      display:
        "NONE": [created_at, news_id, show, file, size, order, all_cultures, _item2item_list]
        "EN":
          - title_i18n_en
          - body_i18n_en
        "RU":
          - title_i18n_ru
          - body_i18n_ru
        "CS":
          - title_i18n_cs
          - body_i18n_cs
        "HU":
          - title_i18n_hu
          - body_i18n_hu
        "PL":
          - title_i18n_pl
          - body_i18n_pl
        "FR":
          - title_i18n_fr
          - body_i18n_fr
        "ZH_CN":
          - title_i18n_zh_CN
          - body_i18n_zh_CN
        "VI":
          - title_i18n_vi
          - body_i18n_vi
        "JA":
          - title_i18n_ja
          - body_i18n_ja
        "ES":
          - title_i18n_es
          - body_i18n_es
        "IT":
          - title_i18n_it
          - body_i18n_it
        "ET":
          - title_i18n_et
          - body_i18n_et
        "NE":
          - title_i18n_ne
          - body_i18n_ne
        "BN":
          - title_i18n_bn
          - body_i18n_bn
        "HE":
          - title_i18n_he
          - body_i18n_he
        "ZH_TW":
          - title_i18n_zh_TW
          - body_i18n_zh_TW
        "DE":
          - title_i18n_de
          - body_i18n_de

      fields:
        file:
          name: File
          type: admin_input_file_tag
          upload_dir: documents
          params:
            include_link: documents
            include_remove: true

        title_i18n_en:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_en:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_ru:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ru:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_cs:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_cs:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_hu:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_hu:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_pl:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_pl:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_fr:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_fr:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_zh_cn:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_zh_cn:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_vi:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_vi:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_it:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_it:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_ja:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ja:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_es:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_es:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_it:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_it:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_et:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_et:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_ne:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_ne:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_bn:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_bn:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_he:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_he:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_zh_tw:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_zh_tw:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6

        title_i18n_de:
          name: Title
          params: disabled=false maxlength=255 style="width:80%"
        body_i18n_de:
          name: Body
          type: textarea_tag
          params: disabled=false size=118x6